### ISSUE TITLE
requesting your data

### ISSUE THREAD

**Issue by mindmad** [lakshay-middha/Crack_Detection_and_Segmentation#1]
Hello, @lakshay-middha  
is it possble to provide the datasets you use for classification and segmentation. and am going to use my local machine can you as well provide how to integrate the data to the model while using my local machine.

**Comment by mindmad** [comment]
I found the classfication datasets, however didn't find the segmantion data. we do u mind  share it with me.

**Comment by lakshay-middha** [comment]
Hey, download the dataset from here.
[https://www.kaggle.com/lakshaymiddha/crack-segmentation-dataset](url)
